-- Design 2A additions: run AFTER supabase/schema.sql.
-- Adds per-worker QR/connection publishing and generic worker events so the
-- shared Vercel dashboard can render QR, status, and live logs purely through
-- Supabase (no tunnel). Safe to run multiple times.

-- Human-friendly worker fields + live WhatsApp connection state and QR.
alter table public.worker_instances
  add column if not exists display_name text,
  add column if not exists wa_connected boolean not null default false,
  add column if not exists wa_number text,
  add column if not exists qr_data text,
  add column if not exists qr_updated_at timestamptz;

-- Live event stream (logs, sheet check results, message sent/failed) that the
-- dashboard subscribes to. Kept small and append-only.
create table if not exists public.worker_events (
  id bigint generated by default as identity primary key,
  worker_id text not null,
  session_id uuid,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists worker_events_worker_created_idx
  on public.worker_events(worker_id, created_at desc);

alter table public.worker_events enable row level security;

-- Realtime publication so the browser receives inserts/updates.
-- Ignore errors if the table is already in the publication.
do $$
begin
  begin
    alter publication supabase_realtime add table public.worker_events;
  exception when duplicate_object then null; end;
  begin
    alter publication supabase_realtime add table public.worker_instances;
  exception when duplicate_object then null; end;
  begin
    alter publication supabase_realtime add table public.monitor_commands;
  exception when duplicate_object then null; end;
end $$;
