-- Supabase control plane for the local WhatsApp worker.
-- Run this in Supabase SQL Editor. OTP/phone authentication is intentionally
-- not part of this schema; use Supabase email/password auth if authentication
-- is added to the Vercel frontend.

create extension if not exists pgcrypto;

create table if not exists public.worker_instances (
  id text primary key,
  status text not null default 'offline' check (status in ('online', 'offline', 'error')),
  metadata jsonb not null default '{}'::jsonb,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.monitor_sessions (
  id uuid primary key default gen_random_uuid(),
  worker_id text not null references public.worker_instances(id) on delete cascade,
  owner_id uuid references auth.users(id) on delete set null,
  lease_token text not null,
  state text not null default 'running' check (state in ('running', 'stopped', 'expired', 'error')),
  config jsonb not null default '{}'::jsonb,
  last_client_seen_at timestamptz not null default now(),
  started_at timestamptz not null default now(),
  stopped_at timestamptz,
  stop_reason text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists monitor_sessions_worker_state_idx
  on public.monitor_sessions(worker_id, state);

create table if not exists public.monitor_commands (
  id uuid primary key default gen_random_uuid(),
  worker_id text not null references public.worker_instances(id) on delete cascade,
  session_id uuid references public.monitor_sessions(id) on delete set null,
  owner_id uuid references auth.users(id) on delete set null,
  command_type text not null check (command_type in ('start_monitoring', 'stop_monitoring', 'send_message', 'logout')),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed')),
  error text,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  completed_at timestamptz
);

create index if not exists monitor_commands_worker_status_idx
  on public.monitor_commands(worker_id, status, created_at);

create table if not exists public.message_history (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete set null,
  worker_id text,
  timestamp timestamptz not null default now(),
  sender text,
  name text,
  phone text,
  status text,
  source text,
  error text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists message_history_owner_timestamp_idx
  on public.message_history(owner_id, timestamp desc);

alter table public.worker_instances enable row level security;
alter table public.monitor_sessions enable row level security;
alter table public.monitor_commands enable row level security;
alter table public.message_history enable row level security;

-- The local worker uses the service-role key and bypasses RLS. Browser access
-- is intentionally deny-by-default until owner-specific policies are added.
-- Add policies only after enabling Supabase Auth and deciding your user model.

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists worker_instances_touch_updated_at on public.worker_instances;
create trigger worker_instances_touch_updated_at
before update on public.worker_instances
for each row execute function public.touch_updated_at();

drop trigger if exists monitor_sessions_touch_updated_at on public.monitor_sessions;
create trigger monitor_sessions_touch_updated_at
before update on public.monitor_sessions
for each row execute function public.touch_updated_at();
